# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
first_tensor = torch.rand(7, 7)
first_tensor

tensor([[3.2957e-01, 3.8095e-01, 2.8443e-01, 9.0189e-01, 3.5958e-01, 6.8460e-01,
         3.5801e-01],
        [1.6492e-01, 6.1171e-01, 1.0779e-01, 9.3203e-01, 7.7832e-01, 7.5182e-01,
         7.5555e-04],
        [1.6413e-01, 7.2584e-02, 4.6052e-01, 2.5569e-01, 4.4302e-01, 2.5534e-01,
         4.7285e-01],
        [4.7121e-01, 3.9701e-02, 2.1180e-01, 5.9211e-01, 1.9261e-01, 9.1390e-01,
         5.2622e-01],
        [4.2752e-01, 8.6403e-01, 3.7291e-01, 8.1424e-01, 1.3210e-01, 4.5884e-01,
         5.3688e-01],
        [4.6295e-01, 9.3482e-01, 2.9807e-01, 1.4783e-01, 2.1381e-01, 6.9301e-01,
         6.5992e-01],
        [4.9219e-01, 2.9676e-03, 5.7077e-01, 7.5476e-01, 6.0800e-01, 3.5992e-02,
         9.2958e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
second_tensor = torch.rand(1, 7)

matmul_result = torch.matmul(first_tensor, second_tensor.T)
matmul_result

tensor([[2.4900],
        [2.4489],
        [1.4994],
        [2.3915],
        [2.4964],
        [2.2942],
        [2.4788]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
torch.manual_seed(0)

result_with_seed = torch.matmul(first_tensor, second_tensor.T)
result_with_seed, result_with_seed.shape

(tensor([[2.4900],
         [2.4489],
         [1.4994],
         [2.3915],
         [2.4964],
         [2.2942],
         [2.4788]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
torch.manual_seed(1234)

torch.cuda.is_available()

first_tensor = torch.rand(2, 3, device="cuda")
second_tensor = torch.rand(2, 3, device="cuda")


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
GPU_result = torch.matmul(first_tensor, second_tensor.T)
GPU_result, GPU_result.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
torch.min(GPU_result), torch.max(GPU_result)

(tensor(0.2786, device='cuda:0'), tensor(0.7668, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
torch.argmin(GPU_result), torch.argmax(GPU_result)

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
torch.manual_seed(7)
first_random_tensor = torch.rand(1, 1, 1, 10)
second_random_tensor = first_random_tensor.squeeze()

first_random_tensor, first_random_tensor.shape, second_random_tensor, second_random_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))